FROM mcr.microsoft.com/devcontainers/javascript-node

USER node

RUN curl -fsSL https://code-server.dev/install.sh | sh

CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080"]
EXPOSE 8080